SHELL=/bin/bash
summary/all.tex: gen
	echo '\summarySection{Loaded Graphs}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{Goal}}{\summaryGraphFile{out/000_g_0_10300000}{\texttt{out/000\_g\_0\_10300000}}}{\summaryGraphFile{out/000_g_0_11310100}{\texttt{out/000\_g\_0\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{Start}}{\summaryGraphFile{out/001_g_1_10300000}{\texttt{out/001\_g\_1\_10300000}}}{\summaryGraphFile{out/001_g_1_11310100}{\texttt{out/001\_g\_1\_11310100}}}' >> summary/all.tex
	echo '\summarySection{Loaded Rules}' >> summary/all.tex
	echo '\summaryRule{Mark for conversion}{\summaryRuleSpan{out/003_r_0_10300000}{out/003\_r\_0\_10300000}}{\summaryRuleSpan{out/004_r_0_11300100}{out/004\_r\_0\_11300100}}{\summaryRuleCombined{out/005_r_0_combined}{out/005\_r\_0\_combined}}{out/006_r_0_constraints.tex}' >> summary/all.tex
	echo '\summaryRule{reattachExternalEdge}{\summaryRuleSpan{out/008_r_1_10300000}{out/008\_r\_1\_10300000}}{\summaryRuleSpan{out/009_r_1_11300100}{out/009\_r\_1\_11300100}}{\summaryRuleCombined{out/010_r_1_combined}{out/010\_r\_1\_combined}}{out/011_r_1_constraints.tex}' >> summary/all.tex
	echo '\summaryDGHyper{\texttt{dg\_0}}{out/013_dg_0_10100}{\texttt{out/013\_dg\_0\_10100}}' >> summary/all.tex
	echo '\summarySection{Product Graphs}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,0\}}}{\summaryGraphFile{out/014_g_2_10300000}{\texttt{out/014\_g\_2\_10300000}}}{\summaryGraphFile{out/014_g_2_11310100}{\texttt{out/014\_g\_2\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,1\}}}{\summaryGraphFile{out/015_g_20_10300000}{\texttt{out/015\_g\_20\_10300000}}}{\summaryGraphFile{out/015_g_20_11310100}{\texttt{out/015\_g\_20\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,2\}}}{\summaryGraphFile{out/016_g_32_10300000}{\texttt{out/016\_g\_32\_10300000}}}{\summaryGraphFile{out/016_g_32_11310100}{\texttt{out/016\_g\_32\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,3\}}}{\summaryGraphFile{out/017_g_34_10300000}{\texttt{out/017\_g\_34\_10300000}}}{\summaryGraphFile{out/017_g_34_11310100}{\texttt{out/017\_g\_34\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,4\}}}{\summaryGraphFile{out/018_g_37_10300000}{\texttt{out/018\_g\_37\_10300000}}}{\summaryGraphFile{out/018_g_37_11310100}{\texttt{out/018\_g\_37\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,5\}}}{\summaryGraphFile{out/019_g_43_10300000}{\texttt{out/019\_g\_43\_10300000}}}{\summaryGraphFile{out/019_g_43_11310100}{\texttt{out/019\_g\_43\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,6\}}}{\summaryGraphFile{out/020_g_55_10300000}{\texttt{out/020\_g\_55\_10300000}}}{\summaryGraphFile{out/020_g_55_11310100}{\texttt{out/020\_g\_55\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,7\}}}{\summaryGraphFile{out/021_g_67_10300000}{\texttt{out/021\_g\_67\_10300000}}}{\summaryGraphFile{out/021_g_67_11310100}{\texttt{out/021\_g\_67\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,8\}}}{\summaryGraphFile{out/022_g_80_10300000}{\texttt{out/022\_g\_80\_10300000}}}{\summaryGraphFile{out/022_g_80_11310100}{\texttt{out/022\_g\_80\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,9\}}}{\summaryGraphFile{out/023_g_87_10300000}{\texttt{out/023\_g\_87\_10300000}}}{\summaryGraphFile{out/023_g_87_11310100}{\texttt{out/023\_g\_87\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,10\}}}{\summaryGraphFile{out/024_g_88_10300000}{\texttt{out/024\_g\_88\_10300000}}}{\summaryGraphFile{out/024_g_88_11310100}{\texttt{out/024\_g\_88\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,11\}}}{\summaryGraphFile{out/025_g_91_10300000}{\texttt{out/025\_g\_91\_10300000}}}{\summaryGraphFile{out/025_g_91_11310100}{\texttt{out/025\_g\_91\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,12\}}}{\summaryGraphFile{out/026_g_98_10300000}{\texttt{out/026\_g\_98\_10300000}}}{\summaryGraphFile{out/026_g_98_11310100}{\texttt{out/026\_g\_98\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,13\}}}{\summaryGraphFile{out/027_g_99_10300000}{\texttt{out/027\_g\_99\_10300000}}}{\summaryGraphFile{out/027_g_99_11310100}{\texttt{out/027\_g\_99\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,14\}}}{\summaryGraphFile{out/028_g_100_10300000}{\texttt{out/028\_g\_100\_10300000}}}{\summaryGraphFile{out/028_g_100_11310100}{\texttt{out/028\_g\_100\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,15\}}}{\summaryGraphFile{out/029_g_101_10300000}{\texttt{out/029\_g\_101\_10300000}}}{\summaryGraphFile{out/029_g_101_11310100}{\texttt{out/029\_g\_101\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,16\}}}{\summaryGraphFile{out/030_g_105_10300000}{\texttt{out/030\_g\_105\_10300000}}}{\summaryGraphFile{out/030_g_105_11310100}{\texttt{out/030\_g\_105\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,17\}}}{\summaryGraphFile{out/031_g_111_10300000}{\texttt{out/031\_g\_111\_10300000}}}{\summaryGraphFile{out/031_g_111_11310100}{\texttt{out/031\_g\_111\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,18\}}}{\summaryGraphFile{out/032_g_113_10300000}{\texttt{out/032\_g\_113\_10300000}}}{\summaryGraphFile{out/032_g_113_11310100}{\texttt{out/032\_g\_113\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,19\}}}{\summaryGraphFile{out/033_g_117_10300000}{\texttt{out/033\_g\_117\_10300000}}}{\summaryGraphFile{out/033_g_117_11310100}{\texttt{out/033\_g\_117\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,20\}}}{\summaryGraphFile{out/034_g_119_10300000}{\texttt{out/034\_g\_119\_10300000}}}{\summaryGraphFile{out/034_g_119_11310100}{\texttt{out/034\_g\_119\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,21\}}}{\summaryGraphFile{out/035_g_123_10300000}{\texttt{out/035\_g\_123\_10300000}}}{\summaryGraphFile{out/035_g_123_11310100}{\texttt{out/035\_g\_123\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,22\}}}{\summaryGraphFile{out/036_g_127_10300000}{\texttt{out/036\_g\_127\_10300000}}}{\summaryGraphFile{out/036_g_127_11310100}{\texttt{out/036\_g\_127\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,23\}}}{\summaryGraphFile{out/037_g_133_10300000}{\texttt{out/037\_g\_133\_10300000}}}{\summaryGraphFile{out/037_g_133_11310100}{\texttt{out/037\_g\_133\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,24\}}}{\summaryGraphFile{out/038_g_135_10300000}{\texttt{out/038\_g\_135\_10300000}}}{\summaryGraphFile{out/038_g_135_11310100}{\texttt{out/038\_g\_135\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,25\}}}{\summaryGraphFile{out/039_g_136_10300000}{\texttt{out/039\_g\_136\_10300000}}}{\summaryGraphFile{out/039_g_136_11310100}{\texttt{out/039\_g\_136\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,26\}}}{\summaryGraphFile{out/040_g_138_10300000}{\texttt{out/040\_g\_138\_10300000}}}{\summaryGraphFile{out/040_g_138_11310100}{\texttt{out/040\_g\_138\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,27\}}}{\summaryGraphFile{out/041_g_139_10300000}{\texttt{out/041\_g\_139\_10300000}}}{\summaryGraphFile{out/041_g_139_11310100}{\texttt{out/041\_g\_139\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,28\}}}{\summaryGraphFile{out/042_g_152_10300000}{\texttt{out/042\_g\_152\_10300000}}}{\summaryGraphFile{out/042_g_152_11310100}{\texttt{out/042\_g\_152\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,29\}}}{\summaryGraphFile{out/043_g_153_10300000}{\texttt{out/043\_g\_153\_10300000}}}{\summaryGraphFile{out/043_g_153_11310100}{\texttt{out/043\_g\_153\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,30\}}}{\summaryGraphFile{out/044_g_154_10300000}{\texttt{out/044\_g\_154\_10300000}}}{\summaryGraphFile{out/044_g_154_11310100}{\texttt{out/044\_g\_154\_11310100}}}' >> summary/all.tex
	echo -n '\summaryGraph' >> summary/all.tex
	echo '{\texttt{p\_\{0,31\}}}{\summaryGraphFile{out/045_g_156_10300000}{\texttt{out/045\_g\_156\_10300000}}}{\summaryGraphFile{out/045_g_156_11310100}{\texttt{out/045\_g\_156\_11310100}}}' >> summary/all.tex
	echo '\summarySection{Flow Solutions, id 0}' >> summary/all.tex
summary.pdf: summary/all.tex
	/mnt/Shared/jlandersen/shared/bin/../bin/mod_post --mode compileSummary
include summary/MakefileImpl
include summary/MakefileDep
include summary/MakefileAllTarget
include summary/MakefileClean
