graph [
	node [ id 0 label "0" ]
	node [ id 1 label "0" ]
	node [ id 2 label "0" ]
	node [ id 3 label "0" ]
	node [ id 4 label "0" ]
	node [ id 5 label "0" ]
	node [ id 6 label "0" ]
	node [ id 7 label "0" ]
	node [ id 8 label "0" ]
	node [ id 9 label "0" ]
	node [ id 10 label "0" ]
	node [ id 11 label "0" ]
	node [ id 12 label "0" ]
	node [ id 13 label "0" ]
	node [ id 14 label "0" ]
	node [ id 15 label "0" ]
	node [ id 16 label "0" ]
	node [ id 17 label "0" ]
	node [ id 18 label "0" ]
	edge [ source 0 target 7 label "-" ]
	edge [ source 1 target 10 label "-" ]
	edge [ source 10 target 11 label "-" ]
	edge [ source 10 target 12 label "-" ]
	edge [ source 10 target 6 label "-" ]
	edge [ source 10 target 7 label "-" ]
	edge [ source 10 target 9 label "-" ]
	edge [ source 11 target 13 label "-" ]
	edge [ source 12 target 13 label "-" ]
	edge [ source 12 target 16 label "-" ]
	edge [ source 12 target 18 label "-" ]
	edge [ source 13 target 14 label "-" ]
	edge [ source 13 target 16 label "-" ]
	edge [ source 13 target 17 label "-" ]
	edge [ source 13 target 18 label "-" ]
	edge [ source 13 target 9 label "-" ]
	edge [ source 14 target 16 label "-" ]
	edge [ source 15 target 16 label "-" ]
	edge [ source 15 target 17 label "-" ]
	edge [ source 15 target 18 label "-" ]
	edge [ source 16 target 18 label "-" ]
	edge [ source 2 target 3 label "-" ]
	edge [ source 2 target 4 label "-" ]
	edge [ source 2 target 5 label "-" ]
	edge [ source 3 target 4 label "-" ]
	edge [ source 4 target 5 label "-" ]
	edge [ source 5 target 8 label "-" ]
	edge [ source 6 target 7 label "-" ]
	edge [ source 6 target 8 label "-" ]
	edge [ source 6 target 9 label "-" ]
]
