graph [
	node [ id 0 label "0" ]
	node [ id 1 label "0" ]
	node [ id 2 label "0" ]
	node [ id 3 label "0" ]
	node [ id 4 label "0" ]
	node [ id 5 label "0" ]
	node [ id 6 label "0" ]
	node [ id 7 label "0" ]
	node [ id 8 label "0" ]
	node [ id 9 label "0" ]
	node [ id 10 label "0" ]
	node [ id 11 label "0" ]
	node [ id 12 label "0" ]
	edge [ source 0 target 11 label "-" ]
	edge [ source 0 target 12 label "-" ]
	edge [ source 0 target 2 label "-" ]
	edge [ source 1 target 4 label "-" ]
	edge [ source 10 target 9 label "-" ]
	edge [ source 11 target 3 label "-" ]
	edge [ source 11 target 6 label "-" ]
	edge [ source 11 target 9 label "-" ]
	edge [ source 12 target 3 label "-" ]
	edge [ source 12 target 6 label "-" ]
	edge [ source 12 target 9 label "-" ]
	edge [ source 2 target 6 label "-" ]
	edge [ source 2 target 7 label "-" ]
	edge [ source 3 target 4 label "-" ]
	edge [ source 3 target 6 label "-" ]
	edge [ source 3 target 8 label "-" ]
	edge [ source 5 target 6 label "-" ]
	edge [ source 5 target 7 label "-" ]
	edge [ source 5 target 8 label "-" ]
	edge [ source 6 target 7 label "-" ]
]
