graph [
	node [ id 0 label "0" ]
	node [ id 1 label "0" ]
	node [ id 2 label "0" ]
	node [ id 3 label "0" ]
	node [ id 4 label "0" ]
	node [ id 5 label "0" ]
	node [ id 6 label "0" ]
	node [ id 7 label "0" ]
	node [ id 8 label "0" ]
	node [ id 9 label "0" ]
	edge [ source 0 target 1 label "-" ]
	edge [ source 0 target 2 label "-" ]
	edge [ source 0 target 3 label "-" ]
	edge [ source 0 target 5 label "-" ]
	edge [ source 2 target 5 label "-" ]
	edge [ source 3 target 7 label "-" ]
	edge [ source 3 target 8 label "-" ]
	edge [ source 4 target 5 label "-" ]
	edge [ source 4 target 7 label "-" ]
	edge [ source 4 target 8 label "-" ]
	edge [ source 5 target 9 label "-" ]
	edge [ source 6 target 7 label "-" ]
	edge [ source 6 target 8 label "-" ]
	edge [ source 6 target 9 label "-" ]
]
